// auto-generated by parse_tiled_maps.py at 2023-02-13 22:26:51.663369

#pragma once

constexpr uint8_t SEGMENT_CNT = 6;
constexpr uint8_t SEGMENT_W = 20;
constexpr uint8_t SEGMENT_H = 4;
constexpr uint8_t NEXT_LEVEL_OPTIONS_CNT = 3;

enum class SegmentLoadOrientation : uint8_t {
    HORIZONTAL,
    VERTICAL,
};

struct Segment {
    uint8_t obstacle_cnt;
    SegmentLoadOrientation load_orientation;
};

const uint8_t PROGMEM SEGMENT_MAPS[SEGMENT_CNT][SEGMENT_H][SEGMENT_W] = {
// lvl1.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,0,0,2,2},
  {3,0,0,0,0,3,3,0,0,0,0,2,3,0,0,0,3,3,0,0}
},
// lvl2.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2},
  {0,2,2,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,2},
  {0,0,0,0,0,0,0,0,0,0,2,0,0,2,0,0,3,0,0,0},
  {0,0,3,3,0,0,0,2,3,3,2,3,3,2,2,2,2,2,2,2}
},
// lvl3.json
{
  {0,2,2,2,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,2,2,2},
  {0,0,3,3,2,3,3,3,3,2,0,0,0,0,2,2,2,0,0,0}
},
// lvl4.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,2,0,0},
  {0,0,0,0,2,0,0,2,0,0,2,0,0,0,0,2,0,2,0,0},
  {1,2,3,3,2,3,3,2,3,3,2,3,2,3,3,2,3,2,3,1}
},
// lvl5.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,2,0,0,0,0},
  {0,0,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0}
},
// lvl6.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {1,1,0,0,0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,0},
  {0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,1,1,0,0,3,3,0,0,3,3,2,3,3,3,0,0}
},
};

const Segment SEGMENTS_METADATA[SEGMENT_CNT] = {
{
    .obstacle_cnt = 7,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 13,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 11,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 21,
    .load_orientation = SegmentLoadOrientation::VERTICAL,
},
{
    .obstacle_cnt = 6,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 9,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
};

const uint8_t SEGMENT_LINKS[SEGMENT_CNT][NEXT_LEVEL_OPTIONS_CNT] = {
{1, 4, 5},
{2, 4, 4},
{3, 4, 4},
{4, 2, 1},
{2, 3, 3},
{4, 1, 3},
};

