// auto-generated by parse_tiled_maps.py at 2023-02-22 21:36:20.266099

#pragma once

constexpr uint8_t SEGMENT_CNT = 9;
constexpr uint8_t SEGMENT_W = 20;
constexpr uint8_t SEGMENT_H = 4;
constexpr uint8_t NEXT_LEVEL_OPTIONS_CNT = 3;

enum class SegmentLoadOrientation : uint8_t {
    HORIZONTAL,
    VERTICAL,
};

struct Segment {
    uint8_t obstacle_cnt;
    SegmentLoadOrientation load_orientation;
};

const uint8_t PROGMEM SEGMENT_MAPS[SEGMENT_CNT][SEGMENT_H][SEGMENT_W] = {
// lvl1.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0},
  {3,0,0,0,3,0,0,0,3,3,0,0,0,2,0,0,2,2,2,0}
},
// lvl2.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,2,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,2,3,3,2,3,3,2,3,2,2,0,0,3,2,0,0,0}
},
// lvl3.json
{
  {0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,2,0,0,0,0,0,1,1,0,2,0,0,0},
  {0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,2,0,0},
  {0,0,2,0,0,0,0,0,3,2,0,0,0,0,3,3,0,0,0,0}
},
// lvl4.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,2,0,0},
  {0,0,0,0,2,0,0,2,0,0,2,0,0,0,0,2,0,2,0,0},
  {0,2,3,3,2,3,3,2,3,3,2,3,2,3,3,2,3,2,3,1}
},
// lvl5.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,2,2,2},
  {0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,2,0,0,0,0},
  {0,0,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0}
},
// lvl6.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,2,0,0,2,0,3,0,0,3,2,0,0},
  {0,0,0,0,0,2,0,0,0,0,0,2,0,2,0,2,2,0,0,0},
  {0,0,0,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,0}
},
// lvl7.json
{
  {0,0,2,2,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,2,0,0,0},
  {0,0,0,0,2,2,0,0,0,0,0,0,0,0,2,0,2,0,2,0},
  {0,2,2,2,0,0,3,3,3,3,2,2,2,3,3,3,2,3,2,0}
},
// lvl8.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,2,2},
  {0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0}
},
// lvl9.json
{
  {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,3,2,0,3,4,0,0,0,2,0,0},
  {0,0,0,2,2,0,0,2,0,2,0,0,2,2,2,0,0,0,0,0},
  {2,0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,0}
},
};

const Segment SEGMENTS_METADATA[SEGMENT_CNT] = {
{
    .obstacle_cnt = 6,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 13,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 11,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 19,
    .load_orientation = SegmentLoadOrientation::VERTICAL,
},
{
    .obstacle_cnt = 7,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 11,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 15,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 6,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
{
    .obstacle_cnt = 10,
    .load_orientation = SegmentLoadOrientation::HORIZONTAL,
},
};

const uint8_t SEGMENT_LINKS[SEGMENT_CNT][NEXT_LEVEL_OPTIONS_CNT] = {
{1, 1, 1},
{2, 3, 7},
{1, 3, 4},
{2, 4, 5},
{1, 5, 6},
{6, 1, 2},
{0, 2, 7},
{8, 6, 4},
{8, 6, 3},
};

